/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserResponseDto } from '../models/user-response-dto';
export interface CompetenceDto {
  date?: string;
  id?: number;
  title?: string;
  type?: string;
  user?: UserResponseDto;
}
