/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OfferResponseDto } from '../models/offer-response-dto';
import { UserResponseDto } from '../models/user-response-dto';
export interface CandidacyResponseUserDto {
  id?: number;
  offerResponseDTO?: OfferResponseDto;
  status?: 'ACCEPTED' | 'PENDING' | 'FAILED';
  userResponseDTO?: UserResponseDto;
}
