/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OfferResponseDto {
  categorie?: string;
  contractType?: string;
  createBy: string;
  createdAt?: string;
  description?: string;
  id?: number;
  location?: string;
  titleJob?: string;
  updateBy?: string;
  updatedAt?: string;
  jobType?:string;
  experience:number;
  company:string;
  userId:number;
}
