/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CategorieRequestDto } from '../models/categorie-request-dto';
export interface OfferRequestDto {
  categorieRequestDTO: CategorieRequestDto;
  contractType: string;
  description: string;
  location: string;
  titleJob: string;
  jobType:string;
  experience:number;
  
}   
