/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AdressDto } from '../models/adress-dto';
export interface UserResponseDto {
  active?: 'ACTIVATED' | 'DESACTIVATED';
  address?: AdressDto;
  age?: number;
  company?: string;
  createAt?: string;
  cv?: string;
  email?: string;
  firstName?: string;
  id?: number;
  lastName?: string;
  role?: 'ADMIN' | 'RECRUITER' | 'CANDIDATE';
  updateAt?: string;
  personalInformation:string;
  function:string;
}
