/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AdressDto } from '../models/adress-dto';
export interface UserRequestDto {
  address?: AdressDto;
  age?: number;
  company?: string;
  cv?: string;
  email: string;
  firstName: string;
  id?: number;
  lastName: string;
  password: string;
  role?: 'ADMIN' | 'RECRUITER' | 'CANDIDATE';
  personalInformation:string;
  function:string;
}
